# -*- coding: utf-8 -*-
"""langchain_with_tongyi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fm5zFWJJVSQJBOd64w3wRturD5rUEoUd
"""

# !pip install --upgrade langchain
from config import *
from langchain.schema import HumanMessage, SystemMessage, AIMessage

# !pip install dashscope --upgrade

# from google.colab import userdata
# key=userdata.get('DASHSCOPE_API_KEY')
# chat = ChatTongyi(amodel="qwen-72b-chat", dashscope_api_key=key)
# chat = load("Tongyi","qwen-72b-chat")
chat= load("Ollama", "gemma:2b")

ret= chat.invoke(
    [
        SystemMessage(content="你是一个旅游助理，名叫yoyo，你可以回答所有旅游相关的问题。"),
        HumanMessage(content="我想去杭州玩，你有什么建议吗？"),
        AIMessage(content="你可以去西湖啊，那里很有名的。"),
        HumanMessage(content="去西湖能玩什么？")
    ]
)

print(ret.content)
print()

template_string = """请改写一段文字成为 {style}风格。
原始内容： ```{text}```
"""

from langchain.prompts import ChatPromptTemplate

prompt_template = ChatPromptTemplate.from_template(template_string)

prompt_template.messages[0].prompt

prompt_template.messages[0].prompt.input_variables

customer_style = "古诗"
customer_email = "春风十里不如你，杭州的夜晚，山外还有更多的山，楼外还有更多的楼。西湖那里的歌舞啊，一直不停。和煦的风吹得每个人都暖洋洋的昏昏欲睡，总觉得自己是在长安，而不是在杭州。"
customer_messages = prompt_template.format_messages(
                    style=customer_style,
                    text=customer_email)

# Call the LLM to translate to the style of the customer message
customer_response = chat.invoke(customer_messages)

print(customer_response.content)
print()

service_reply = """
僵卧孤村不自哀,尚思为国戌轮台。
夜阑卧听风吹雨,铁马冰河入梦来。
"""
service_style = "散文"

service_messages = prompt_template.format_messages(
    style=service_style,
    text=service_reply)

# print(service_messages[0].content)
service_response = chat.invoke(service_messages)
print(service_response.content)